# Generated by Django 5.2.17 on 2026-08-09 16:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_events_even_status_5709b6_idx_and_more'),
        ('operations', '0002_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='eventtask',
            index=models.Index(fields=['due_date'], name='operations__due_dat_82acd6_idx'),
        ),
        migrations.AddIndex(
            model_name='eventtask',
            index=models.Index(fields=['assigned_to'], name='operations__assigne_93d817_idx'),
        ),
    ]
