# Generated by Django 5.2.17 on 2026-08-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
